In [1]:
import pandas as pd

In [2]:
raw_csv_data = pd.read_csv('Absenteeism_data.csv')

In [3]:
raw_csv_data.head(5)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [4]:
df = raw_csv_data.copy()

In [5]:
# Helps display every row and column in a data set. 
# This is more applied to larger datasets
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [6]:
display(df)

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
5     3                  23  10/07/2015                     179   
6    10                  22  17/07/2015                     361   
7    20                  23  24/07/2015                     260   
8    14                  19  06/07/2015                     155   
9     1                  22  13/07/2015                     235   
10   20                   1  20/07/2015                     260   
11   20                   1  14/07/2015                     260   
12   20                  11  15/07/2015                     260   
13    3                  11  15/07/2015                     179   
14    3                  23  15/07/2015                     179   
15   24                  14  17/07/2015                     246   
16    3                  23  17/07/2015                     179   
17    3                  21  27/07/2015                     179   
18    6                  11  30/07/2015                     189   
19   33                  23  05/08/2015                     248   
20   18                  10  12/08/2015                     330   
21    3                  11  03/08/2015                     179   
22   10                  13  10/08/2015                     361   
23   20                  28  14/08/2015                     260   
24   11                  18  17/08/2015                     289   
25   10                  25  24/08/2015                     361   
26   11                  23  04/08/2015                     289   
27   30                  28  12/08/2015                     157   
28   11                  18  19/08/2015                     289   
29    3                  23  28/08/2015                     179   
30    3                  18  17/08/2015                     179   
31    2                  18  27/08/2015                     235   
32    1                  23  27/08/2015                     235   
33    2                  18  17/08/2015                     235   
34    3                  23  17/08/2015                     179   
35   10                  23  17/08/2015                     361   
36   11                  24  04/08/2015                     289   
37   19                  11  20/08/2015                     291   
38    2                  28  21/08/2015                     235   
39   20                  23  28/08/2015                     260   
40   27                  23  01/09/2015                     184   
41   34                  23  07/09/2015                     118   
42    3                  23  01/09/2015                     179   
43    5                  19  08/09/2015                     235   
44   14                  23  09/09/2015                     155   
45   34                  23  13/09/2015                     118   
46    3                  23  14/09/2015                     179   
47   15                  23  24/09/2015                     291   
48   20                  22  04/09/2015                     260   
49   15                  14  14/09/2015                     291   
50   20                   0  21/09/2015                     260   
51   29                   0  28/09/2015                     225   
52   28                  23  08/09/2015                     225   
53   34                  23  15/09/2015                     118   
54   11                   0  22/09/2015                     289   
55   36                   0  29/09/2015                     118   
56   28                  18  16/09/2015                     225   
57    3                  23  23/09/2015                     179   
58   13                   0  30/09/2015             

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
ID                           700 non-null int64
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.7+ KB


In [8]:
type(df)

pandas.core.frame.DataFrame

### Drop "ID" Column

In [9]:
df = df.drop(['ID'], axis =1)

In [10]:
df.head(5)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

## Reasons for Absence column

In [11]:
df['Reason for Absence'].head(5)

0    26
1     0
2    23
3     7
4    23
Name: Reason for Absence, dtype: int64

In [12]:
# print the maximum and min values in our dataframe
df['Reason for Absence'].min(), df['Reason for Absence'].max()

(0, 28)

In [13]:
# print out unique values i our column
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [14]:
# printing the lengthof the unique vales shows us the number of different reasons for absenteesm at work
# In our own case, 28 reasons
len(df['Reason for Absence'].unique())

28

In [15]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [16]:
# sorting the unique valeus allows us to easily spot the missing values in our column
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

## Categorical Nominal Data
Observe that the 'Abssence"column is inputed with numemrical values meaning represnting different reasons in the feature description. However, when applying these values in our model, we'll experience a problem where rreasons with higher values say 20-28 are ranked higher than values below 20. This will go a long way in negatively affecting our model. We adress this problem by introducing dummy variables which gives us a 1 or 0 value for each value of the 'Reason' column

In [17]:
reason_columns = pd.get_dummies(df['Reason for Absence'])
reason_columns.head(5)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   19  21  22  23  24  25  26  27  28  
0   0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0   0  
2   0   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0   0  
4   0   0   0   1   0   0   0   0   0

We cratet anew column "check" to verify if a particular value is missing in a row

In [18]:
reason_columns['check'] = reason_columns.sum(axis =1)
reason_columns.head(5)

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  \
0  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
1  1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   

   22  23  24  25  26  27  28  check  
0   0   0   0   0   1   0   0      1  
1   0   0   0   0   0   0   0      1  
2   0   1   0   0   0   0   0      1  
3   0   0   0   0   0   0   0      1  
4   0   1   0   0   0   0   0      1

In [19]:
# verify that the valeus in our check column is only 1
reason_columns['check'].unique()

array([1])

Being satisfied with the check we can now remove the check column from our dummy variables

In [20]:
reason_columns = reason_columns.drop(['check'], axis =1)
reason_columns.head(3)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   19  21  22  23  24  25  26  27  28  
0   0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0   0  
2   0   0   0   1   0   0   0   0   0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(9), object(1)
memory usage: 60.2+ KB


In order to avoid multicollinearity issues, we drop the "Reason 0" column). 

In [22]:
# Drop first column
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first=True)
reason_columns.head(2)

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   21  22  23  24  25  26  27  28  
0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0

## Group the Reasons for Absence

Since we have too many coluns for analysis, we group the various reasons for absence to make things easy

In [23]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

In [24]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [25]:
df = df.drop(['Reason for Absence'], axis=1)

In [26]:
df.head(2)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   

   Absenteeism Time in Hours  
0                          4  
1                          0

The process of re-organizing/grouping a certain type of vaiables into groups in a regression analysis can be called regression analysis

In [27]:
reason_columns.loc[:, 1:14].max(axis=1).head(15)

0     0
1     0
2     0
3     1
4     0
5     0
6     0
7     0
8     0
9     0
10    1
11    1
12    1
13    1
14    0
dtype: uint8

In [28]:
# Let's group our dummy variabes based on similar reasons
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

In [29]:
reason_type_1.head(5)

0    0
1    0
2    0
3    1
4    0
dtype: uint8

## Concatenate Column Values

In [30]:
df.head(2)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   

   Absenteeism Time in Hours  
0                          4  
1                          0

In [31]:
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis=1)

In [32]:
df.head(2)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0

In [33]:
# Assign column names to the new columns
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [34]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1','Reason_2', 'Reason_3', 'Reason_4']

In [35]:
df.columns = column_names

In [36]:
df.head(1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
Reason_1                     700 non-null uint8
Reason_2                     700 non-null uint8
Reason_3                     700 non-null uint8
Reason_4                     700 non-null uint8
dtypes: float64(1), int64(8), object(1), uint8(4)
memory usage: 57.5+ KB


## Reordering Columns

In [37]:
column_names_reorder = ['Reason_1','Reason_2', 'Reason_3', 'Reason_4','Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets', 'Absenteeism Time in Hours'] 
df = df[column_names_reorder]
df.head(1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
Reason_1                     700 non-null uint8
Reason_2                     700 non-null uint8
Reason_3                     700 non-null uint8
Reason_4                     700 non-null uint8
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(8), object(1), uint8(4)
memory usage: 57.5+ KB


## Creat a Checkpoint
Creating checkpoints allows us store the current version of our work

In [38]:
df_reason_mod = df.copy()

In [39]:
df_reason_mod.head(5)

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

Now that we've created our checkpoint, we'll keep using the new df_reason_mod dataframe and preserve the old df dataframe. We can always fall back to the initial df dataframe should we encounter problems along the way.

## Workinng on the Date Column

In [40]:
df_reason_mod['Date'].head()

0    07/07/2015
1    14/07/2015
2    15/07/2015
3    16/07/2015
4    23/07/2015
Name: Date, dtype: object

In [41]:
# Check for data type
# Every dataframe column comes as a Series data type.
type(df_reason_mod['Date'])

pandas.core.series.Series

In [42]:
# However, our column values still maintain their data types
type(df_reason_mod['Date'][0])

str

In [43]:
# we convert the date column type to a time stamp
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'])

In [44]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

In [45]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')

In [46]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

In [47]:
type(df_reason_mod['Date'])

pandas.core.series.Series

In [48]:
type(df_reason_mod['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [49]:
# Extract the MOnth value
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [50]:
df_reason_mod['Date'][0].month

7

In [51]:
df_reason_mod.shape

(700, 14)

In [52]:
list_months =[]
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)
    
    
list_months

[7,
 7,
 7,
 7,
 7,
 10,
 7,
 7,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 5,
 12,
 3,
 10,
 8,
 8,
 8,
 4,
 12,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 4,
 8,
 8,
 8,
 1,
 7,
 1,
 8,
 9,
 9,
 9,
 9,
 4,
 9,
 9,
 9,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 11,
 9,
 9,
 6,
 10,
 10,
 10,
 10,
 10,
 6,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 4,
 5,
 12,
 11,
 2,
 9,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 2,
 10,
 11,
 11,
 1,
 1,
 2,
 2,
 3,
 4,
 8,
 9,
 10,
 11,
 12,
 12,
 11,
 12,
 12,
 6,
 4,
 5,
 5,
 6,
 7,
 7,
 8,
 11,
 12,
 12,
 1,
 1,
 1,
 11,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 3,
 10,
 11,
 11,
 12,
 12,
 8,
 9,
 2,
 9,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 8,
 3,
 3,
 2,
 3,
 4,
 4,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 4,
 12,
 4,
 4,
 4,
 4,
 6,
 7,
 8,
 8,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 8,
 4,
 4,
 5,
 2,
 3,
 3,
 11,
 9,
 10,
 4,
 11,
 5,
 5,
 5,
 5,
 11,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 7,
 8,
 9,
 10,
 6,
 6

In [53]:
# let's verify if the all our values are included
len(list_months)

700

In [54]:
df_reason_mod['Month Values'] = list_months

In [55]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Values  
0         2     1                          4             7  
1         1     0                          0             7  
2         0     0                          2             7  
3         2     0                          4             7  
4         2     1                          2             7

## Extract the Day of the Week

In [56]:
df_reason_mod['Date'][3].weekday()

3

In [57]:
df_reason_mod['Date'][3]

Timestamp('2015-07-16 00:00:00')

In [58]:
# we create  function that extracts days of the week 
def day_of_week(date_value):
    return date_value.weekday()

In [59]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(day_of_week)

In [60]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Values  Day of the Week  
0         2     1                          4             7                1  
1         1     0                          0             7                1  
2         0     0                          2             7                2  
3         2     0                          4             7                3  
4         2     1                          2             7                3

## Dropping the Date Column

In [61]:
df_reason_mod =  df_reason_mod.drop(['Date'], axis =1)

In [62]:
df_reason_mod.head()
df_reason_mod.shape

(700, 15)

In [63]:
col_m = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
        'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Values', 'Day of the Week']

In [64]:
df_reason_mod.columns = col_m
df_reason_mod.head()
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
Reason_1                     700 non-null uint8
Reason_2                     700 non-null uint8
Reason_3                     700 non-null uint8
Reason_4                     700 non-null uint8
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
Month Values                 700 non-null int64
Day of the Week              700 non-null int64
dtypes: float64(1), int64(10), uint8(4)
memory usage: 63.0 KB


In [65]:
# Let's reorder our columns by bringing the newly created ones at the date column position
columns_mod = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values', 'Day of the Week','Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education','Children', 'Pets', 'Absenteeism Time in Hours']

In [66]:
df_reason_mod = df_reason_mod[columns_mod]
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

## Checkpoint

In [67]:
df_reason_date_mod = df_reason_mod.copy()

In [68]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

## Analyzing the Next 5 Columns

In [69]:
type(df_reason_date_mod['Transportation Expense'][0])

numpy.int64

In [70]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [71]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [72]:
type(df_reason_date_mod['Body Mass Index'][0])

numpy.int64

In [73]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

The above 5 columns are are in a good state and will be highly useful to our model

## 'Educaton', 'Children', 'Pets'
Education columns has categorical variables, we'll take time to explore them one after the other.

In [74]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [75]:
# let's check the unique valeus under the education column
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4])

In [76]:
# Let's check educational qualification with the highest number of staff
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64


From the data dictionary, we learnt that:

1 ---- High Schoo

2 --- Graduate

3 ---- PG

4 ---- A masters or Doctorate

Since the proportion between 2,3&4 is not much, We shall map them under a single category

In [77]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [78]:
df_reason_date_mod['Education'].unique()

array([0, 1])

In [79]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

## Final Checkpoint

In [80]:
df_processed = df_reason_date_mod.copy()
df_processed.head(15)

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0          0         0         0         1             7                1   
1          0         0         0         0             7                1   
2          0         0         0         1             7                2   
3          1         0         0         0             7                3   
4          0         0         0         1             7                3   
5          0         0         0         1            10                2   
6          0         0         0         1             7                4   
7          0         0         0         1             7                4   
8          0         0         1         0             6                6   
9          0         0         0         1             7                0   
10         1         0         0         0             7                0   
11         1         0         0         0             7                1   
12         1         0         0         0             7                2   
13         1         0         0         0             7                2   
14         0         0         0         1             7                2   

    Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                      289                36   33                  239.554   
1                      118                13   50                  239.554   
2                      179                51   38                  239.554   
3                      279                 5   39                  239.554   
4                      289                36   33                  239.554   
5                      179                51   38                  239.554   
6                      361                52   28                  239.554   
7                      260                50   36                  239.554   
8                      155                12   34                  239.554   
9                      235                11   37                  239.554   
10                     260                50   36                  239.554   
11                     260                50   36                  239.554   
12                     260                50   36                  239.554   
13                     179                51   38                  239.554   
14                     179                51   38                  239.554   

    Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                30          0         2     1                          4  
1                31          0         1     0                          0  
2                31          0         0     0                          2  
3                24          0         2     0                          4  
4                30          0         2     1                          2  
5                31          0         0     0                          2  
6                27          0         1     4                          8  
7                23          0         4     0                          4  
8                25          0         2     0                         40  
9                29          1         1     1                          8  
10               23          0         4     0                          8  
11               23          0         4     0                          8  
12               23          0         4     0                          8  
13               31          0         0     0                          1  
14               31          0         0     0                          4

In [81]:
df_processed.to_csv('Absenteeism_processed.csv', index=False)

## Machine Learning
### creating a Logistic Regresson

In [82]:
import numpy as np

In [83]:
# we eyeball our data
df_processed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   
5         0         0         0         1            10                2   
6         0         0         0         1             7                4   
7         0         0         0         1             7                4   
8         0         0         1         0             6                6   
9         0         0         0         1             7                0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2  
5               31          0         0     0                          2  
6               27          0         1     4                          8  
7               23          0         4     0                          4  
8               25          0         2     0                         40  
9               29          1         1     1                          8

## create the target
For this task, we'll be classifying peopl into classes. **Moderately Absent** and **Excessively Absent**
We take the mean value of the target cell. Anythign above he median will be excessive, anythig below he median will be normal

In [84]:
# We find the median
df_processed['Absenteeism Time in Hours'].median()

3.0

In [85]:
#Where column> median =1 else =0
target = np.where(df_processed['Absenteeism Time in Hours']>df_processed['Absenteeism Time in Hours'].median(),1,0)

In [86]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [87]:
# we add the new colun to our data
df_processed['Excessive_Absenteeism'] = target

In [88]:
df_processed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive_Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [89]:
# we'll see that roughly half of the targets are zeros while the rest 1s
target.sum()/target.shape[0]

0.45571428571428574

The value above shows that abut 46% of the targets are 1s leaving about 54% as 0s.

In [90]:
data_with_targets = df_processed.drop(['Absenteeism Time in Hours', 'Education', 'Pets', 'Age'], axis =1)

In [91]:
# let's check if the two variables are same using a new technique
data_with_targets is df_processed

False

## Select the inputs for regression


In [92]:
data_with_targets.shape

(700, 12)

In [93]:
data_with_targets.iloc[:, :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0           0         0         0         1             7                1   
1           0         0         0         0             7                1   
2           0         0         0         1             7                2   
3           1         0         0         0             7                3   
4           0         0         0         1             7                3   
5           0         0         0         1            10                2   
6           0         0         0         1             7                4   
7           0         0         0         1             7                4   
8           0         0         1         0             6                6   
9           0         0         0         1             7                0   
10          1         0         0         0             7                0   
11          1         0         0         0             7                1   
12          1         0         0         0             7                2   
13          1         0         0         0             7                2   
14          0         0         0         1             7                2   
15          1         0         0         0             7                4   
16          0         0         0         1             7                4   
17          0         0         1         0             7                0   
18          1         0         0         0             7                3   
19          0         0         0         1             5                4   
20          1         0         0         0            12                1   
21          1         0         0         0             3                6   
22          1         0         0         0            10                3   
23          0         0         0         1             8                4   
24          0         0         1         0             8                0   
25          0         0         0         1             8                0   
26          0         0         0         1             4                2   
27          0         0         0         1            12                1   
28          0         0         1         0             8                2   
29          0         0         0         1             8                4   
30          0         0         1         0             8                0   
31          0         0         1         0             8                3   
32          0         0         0         1             8                3   
33          0         0         1         0             8                0   
34          0         0         0         1             8                0   
35          0         0         0         1             8                0   
36          0         0         0         1             4                2   
37          1         0         0         0             8                3   
38          0         0         0         1             8                4   
39          0         0         0         1             8                4   
40          0         0         0         1             1                4   
41          0         0         0         1             7                3   
42          0         0         0         1             1                4   
43          0         0         1         0             8                6   
44          0         0         0         1             9                2   
45          0         0         0         1             9                6   
46          0         0         0         1             9                0   
47          0         0         0         1             9                3   
48          0         0         0         1             4                3   
49          1         0         0         0             9                0   
50          0         0    

In [94]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

## Standardize the data

In [95]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()
# the object we jsut created will take the mean and divide by the standard deviation for each point in our data variablewise

In [96]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [97]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [98]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.80633129,
         0.76743118,  0.88046927],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.80633129,
         1.00263338, -0.01928035],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.80633129,
         1.00263338, -0.91902997],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.85378935,
        -0.40857982, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.85378935,
        -0.40857982, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.85378935,
        -0.40857982, -0.01928035]])

In [99]:
scaled_inputs.shape

(700, 11)

## OverFitting & Underfitting

Overfitting occurs when the model learns to predict the data so well that when appplied i real life o new data, it fails misserably.One way to deal withover fitting is by hiding a small part of the data set from the algorithm

## Split the data

In [100]:
from sklearn.model_selection import train_test_split 

In [101]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, target, train_size=0.8, random_state=20)

In [102]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [103]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## The Logistoc Regresson Model


In [104]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [105]:
reg = LogisticRegression()

In [106]:
reg.fit(x_train, y_train)

/home/dangote/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [107]:
round(reg.score(x_train, y_train), 2)*100

76.0

## Manually check accuracy

In [108]:
# Find model putput and compare them with the target
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [109]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [110]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [111]:
np.sum(model_outputs==y_train)

428

In [112]:
#Accuracy = correct predictions/observation
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7642857142857142

## Finding the intercept and coeeficient

In [113]:
reg.intercept_

array([-0.22672598])

In [114]:
reg.coef_

array([[ 2.01820689,  0.30458028,  1.46074976,  1.27443801,  0.01835844,
        -0.08959537,  0.59063433, -0.01360498, -0.01012292,  0.28283932,
         0.39688753]])

In [115]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Children'],
      dtype=object)

In [116]:
feature_name =unscaled_inputs.columns.values

In [117]:
sumry_table = pd.DataFrame(columns=["Feature Name"], data=feature_name)

sumry_table['coefficient'] = np.transpose(reg.coef_)

sumry_table

Feature Name  coefficient
0                  Reason_1     2.018207
1                  Reason_2     0.304580
2                  Reason_3     1.460750
3                  Reason_4     1.274438
4              Month Values     0.018358
5           Day of the Week    -0.089595
6    Transportation Expense     0.590634
7          Distance to Work    -0.013605
8   Daily Work Load Average    -0.010123
9           Body Mass Index     0.282839
10                 Children     0.396888

In [118]:
sumry_table.index = sumry_table.index +1
sumry_table.loc[0] = ['Intercept', reg.intercept_[0]]
sumry_table= sumry_table.sort_index()
sumry_table

Feature Name  coefficient
0                 Intercept    -0.226726
1                  Reason_1     2.018207
2                  Reason_2     0.304580
3                  Reason_3     1.460750
4                  Reason_4     1.274438
5              Month Values     0.018358
6           Day of the Week    -0.089595
7    Transportation Expense     0.590634
8          Distance to Work    -0.013605
9   Daily Work Load Average    -0.010123
10          Body Mass Index     0.282839
11                 Children     0.396888

## Interpreting the coefficients
The closer the weights to 0, the smaller to the weight

In [119]:
sumry_table['Odds_ratio'] = np.exp(sumry_table.coefficient)

In [120]:
sumry_table

Feature Name  coefficient  Odds_ratio
0                 Intercept    -0.226726    0.797139
1                  Reason_1     2.018207    7.524820
2                  Reason_2     0.304580    1.356056
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
5              Month Values     0.018358    1.018528
6           Day of the Week    -0.089595    0.914301
7    Transportation Expense     0.590634    1.805133
8          Distance to Work    -0.013605    0.986487
9   Daily Work Load Average    -0.010123    0.989928
10          Body Mass Index     0.282839    1.326892
11                 Children     0.396888    1.487189

In [121]:
# we sort the valeus i respect to a given column
sumry_table.sort_values('Odds_ratio', ascending=False)

Feature Name  coefficient  Odds_ratio
1                  Reason_1     2.018207    7.524820
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
7    Transportation Expense     0.590634    1.805133
11                 Children     0.396888    1.487189
2                  Reason_2     0.304580    1.356056
10          Body Mass Index     0.282839    1.326892
5              Month Values     0.018358    1.018528
9   Daily Work Load Average    -0.010123    0.989928
8          Distance to Work    -0.013605    0.986487
6           Day of the Week    -0.089595    0.914301
0                 Intercept    -0.226726    0.797139

A feature is not particularly important;

- if its coefficient is around 0
- if its odds ratio is around 1

Note, when we standardized variables, it is advisable not to standardize the dummies. For that, we'll have to eedit our code where we standardized our variables.

In [122]:
## Creating a Custom SCaler to Standardize Only Numeric Features
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, x, y=None):
        self.scaler.fit(x[self.columns], y)
        self.mean_ = np.mean(x[self.columns])
        self.var_ =np.var(x[self.columns])
        return self
    
    def transform(self, x, y=None, copy=None):
        init_col_order = x.columns
        x_scaled = pd.DataFrame(self.scaler.transform(x[self.columns]), columns=self.columns)
        x_not_scaled = x.loc[:, ~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled, x_scaled], axis=1)[init_col_order]

In [123]:
# We create a new varibale that hold the columns we need to scale
# We refer back to our #unscaled_inputs columns

unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Children'],
      dtype=object)

In [124]:
columns_to_scale = ['Month Values','Day of the Week', 'Transportation Expense', 'Distance to Work',
        'Daily Work Load Average', 'Body Mass Index','Children',]

In [125]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [126]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Values', 'Day of the Week',
                      'Transportation Expense', 'Distance to Work',
                      'Daily Work Load Average', 'Body Mass Index',
                      'Children'],
             copy=None, with_mean=None, with_std=None)

In [127]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [128]:
scaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1      0.030796        -0.800950   
1         0         0         0         0      0.030796        -0.800950   
2         0         0         0         1      0.030796        -0.232900   
3         1         0         0         0      0.030796         0.335149   
4         0         0         0         1      0.030796         0.335149   

   Transportation Expense  Distance to Work  Daily Work Load Average  \
0                1.005844          0.412816                -0.806331   
1               -1.574681         -1.141882                -0.806331   
2               -0.654143          1.426749                -0.806331   
3                0.854936         -1.682647                -0.806331   
4                1.005844          0.412816                -0.806331   

   Body Mass Index  Children  
0         0.767431  0.880469  
1         1.002633 -0.019280  
2         1.002633 -0.919030  
3        -0.643782  0.880469  
4         0.767431  0.880469

## Interpreting the Important Coefficients

In [129]:
# we sort the valeus i respect to a given column
# remember that the further away from 0 a coeffcient is, the bigger its importance 
sumry_table.sort_values('Odds_ratio', ascending=False)

Feature Name  coefficient  Odds_ratio
1                  Reason_1     2.018207    7.524820
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
7    Transportation Expense     0.590634    1.805133
11                 Children     0.396888    1.487189
2                  Reason_2     0.304580    1.356056
10          Body Mass Index     0.282839    1.326892
5              Month Values     0.018358    1.018528
9   Daily Work Load Average    -0.010123    0.989928
8          Distance to Work    -0.013605    0.986487
6           Day of the Week    -0.089595    0.914301
0                 Intercept    -0.226726    0.797139

From above table, we observe that the Reasons variables are of higher importance to our model, Day of the week, Age, Pets, Education all have poor valeus not too far away from 0. This indicates how less important they affect our prediction.

## Simplifying the model(Backward Elimination)

We'll use backward elimination toremove all features that have close to no contribution to our model.

In [130]:
# we manuay removed unwanted columns from the columns to scale variable
sumry_table.sort_values('Odds_ratio', ascending=False)


Feature Name  coefficient  Odds_ratio
1                  Reason_1     2.018207    7.524820
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
7    Transportation Expense     0.590634    1.805133
11                 Children     0.396888    1.487189
2                  Reason_2     0.304580    1.356056
10          Body Mass Index     0.282839    1.326892
5              Month Values     0.018358    1.018528
9   Daily Work Load Average    -0.010123    0.989928
8          Distance to Work    -0.013605    0.986487
6           Day of the Week    -0.089595    0.914301
0                 Intercept    -0.226726    0.797139

## Testing The Model

In [131]:
round(reg.score(x_test, y_test), 2)*100

74.0

In [132]:
# A better way to view our model predicted output is by printing out the probabilities
# The first column =0 probality, second =1 probaities
predicted_proba = reg.predict_proba(x_test)
predicted_proba 

array([[0.78262815, 0.21737185],
       [0.60353624, 0.39646376],
       [0.45692546, 0.54307454],
       [0.80370109, 0.19629891],
       [0.07634123, 0.92365877],
       [0.2980815 , 0.7019185 ],
       [0.24126161, 0.75873839],
       [0.06804446, 0.93195554],
       [0.7474479 , 0.2525521 ],
       [0.78418216, 0.21581784],
       [0.38264536, 0.61735464],
       [0.24541156, 0.75458844],
       [0.06329931, 0.93670069],
       [0.61103277, 0.38896723],
       [0.1431606 , 0.8568394 ],
       [0.56472246, 0.43527754],
       [0.40469079, 0.59530921],
       [0.43192104, 0.56807896],
       [0.23979167, 0.76020833],
       [0.04798899, 0.95201101],
       [0.72326237, 0.27673763],
       [0.7955474 , 0.2044526 ],
       [0.46077679, 0.53922321],
       [0.48065635, 0.51934365],
       [0.18678878, 0.81321122],
       [0.74213657, 0.25786343],
       [0.539073  , 0.460927  ],
       [0.88751763, 0.11248237],
       [0.2211046 , 0.7788954 ],
       [0.78714473, 0.21285527],
       [0.

In [133]:
predicted_proba.shape

(140, 2)

In [134]:
# Let's check the result of excessive absenteeism
predicted_proba[:, 1]

array([0.21737185, 0.39646376, 0.54307454, 0.19629891, 0.92365877,
       0.7019185 , 0.75873839, 0.93195554, 0.2525521 , 0.21581784,
       0.61735464, 0.75458844, 0.93670069, 0.38896723, 0.8568394 ,
       0.43527754, 0.59530921, 0.56807896, 0.76020833, 0.95201101,
       0.27673763, 0.2044526 , 0.53922321, 0.51934365, 0.81321122,
       0.25786343, 0.460927  , 0.11248237, 0.7788954 , 0.21285527,
       0.41918928, 0.75013605, 0.67993595, 0.61954479, 0.2044526 ,
       0.56499209, 0.265528  , 0.75410627, 0.53642547, 0.55652984,
       0.22755807, 0.43983259, 0.24860665, 0.08871276, 0.88751658,
       0.64809452, 0.70923342, 0.22858531, 0.24321195, 0.19097291,
       0.51623262, 0.05478237, 0.68458299, 0.23739233, 0.86519987,
       0.44940588, 0.95528144, 0.25253291, 0.06966042, 0.06723719,
       0.73021369, 0.64744404, 0.24621124, 0.82500157, 0.29738979,
       0.21760132, 0.00899383, 0.25492168, 0.77867334, 0.39449757,
       0.25728749, 0.07553823, 0.9004099 , 0.53228272, 0.60000

## Save The Model
We'll use **pickle** to save our model. Pickle is python module used to convert a python object into a character stream

In [135]:
import pickle

In [136]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [137]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)

## Using the Absenteeism module 

In [138]:
from absenteeism_module import *

In [139]:
pd.read_csv('Absenteeism_new_data.csv').head()

ID  Reason for Absence        Date  Transportation Expense  \
0  22                  27  01/06/2018                     179   
1  10                   7  04/06/2018                     361   
2  14                  23  06/06/2018                     155   
3  17                  25  08/06/2018                     179   
4  14                  10  08/06/2018                     155   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                26   30                  237.656               19          3   
1                52   28                  237.656               27          1   
2                12   34                  237.656               25          1   
3                22   40                  237.656               22          2   
4                12   34                  237.656               25          1   

   Children  Pets  
0         0     0  
1         1     4  
2         2     0  
3         2     0  
4         2     0

In [140]:
model = absenteeism_model('model', 'scaler')

In [141]:
model.load_and_clean_data('Absenteeism_new_data.csv')

KeyError: "['Daily Work Load Average', 'Month Values', 'Distance to Work', 'Day of the Week'] not in index"

In [ ]:
model.predicted_outputs()